version: "2.4"

services:

  jenkins:
    build:
      context: ./docker
    volumes:
      - ./jenkins_home:/var/jenkins_home
    ports:
      # HTTP
      - 8080:8080
      # JNLP
      - 50000:50000
